### ISSUE TITLE
iframes only work when pressing knit html button in rstudio

### ISSUE THREAD

**Issue by sckott** [plotly/plotly.R#12]
Or at least for some people the hook only works when pressing knit html button in rstudio.  

Perhaps we need to edit the knit hook to make it work in any context.

**Comment by ouzor** [comment]
Thanks!
I made a short comparison of different interactive visualization packages in R, including plotly, see here: http://ouzor.github.io/blog/2014/11/21/interactive-visualizations.html
I like very much the idea of turning an existing ggplot2 object to a nice interactive version. However, as a data scientist I work a lot with confidential data and can not make any of that public, which to me seems that I can not use the free version of plotly at all...

**Comment by mkcor** [comment]
Hi @ouzor 

We definitely understand that’s a concern. Thanks for asking. A couple thoughts. 

You [control the privacy](https://plot.ly/r/privacy/) of your data, and can make your work public or keep it private (like Google Docs or GitHub). 

You own your data; we don’t make an IP claim to it. We also have an [on-premise version](https://plot.ly/product/enterprise/) of plotly you can run on your own servers. Would any of these options work? Let me know if we can help with anything.

**Comment by ouzor** [comment]
Thanks a lot @mkcor, I'll take a closer look at these options!

**Comment by makis23** [comment]
why does this not work??
library(shiny)
library(plotly)
# Rely on the 'WorldPhones' dataset in the datasets
# package (which generally comes preloaded).
library(datasets)

# Define a server for the Shiny app
shinyServer(function(input, output) {
  
  # Fill in the spot we created for a plot
  output$phonePlot <- renderPlotly({
    
    # Render a barplot
   gg <- barplot(WorldPhones[,input$region]*1000, 
            main=input$region,
            ylab="Number of Telephones",
            xlab="Year")
  })
  
  p <- ggplotly(gg,session="knitr")
  p
})

**Comment by aniruhil** [comment]
Despite following @mkcor's fix that seemed to work for @ouzor, I run into the listed error msg when running Knit HTML and when executing the code line-by-line from inside RStudio.  
<code>
```{r, plotly=TRUE}
require(ggplot2)
gg <- ggplot(cars) + geom_point(aes(speed, dist))
gg

require(plotly)
py <- plotly("aniruhil", "maskedkey")
py$ggplotly(gg, session="knitr")
```
</code>
Quitting from lines 27-30 (testingplotly.Rmd) 
Error in eval(expr, envir, enclos) : attempt to apply non-function
Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval
Execution halted

**Comment by cpsievert** [comment]
The interface has changed quite a bit since this thread. You should only need this:

```r
library(plotly)
gg <- ggplot(cars) + geom_point(aes(speed, dist))
ggplotly(gg)
```

**Comment by aniruhil** [comment]
thanks Carson
