### ISSUE TITLE
ggplotly - axis titles still overlapping with labels when converting faceted plot

### ISSUE THREAD

**Issue by hms1** [plotly/plotly.R#1224]
The issue with axis titles overlapping with axis labels, fixed in the latest version of plotly, appears to still be present when using ggplotly to convert a **faceted** ggplot.

When converting an unfaceted ggplot, the new `automargin=TRUE` attribute works perfectly:

```r
mpg_plot <- mpg %>%
  ggplot(aes(x = cyl, fill = trans)) +
  geom_bar() 

ggplotly(mpg_plot) %>% 
  layout( 
  xaxis = list(automargin=TRUE), 
  yaxis = list(automargin=TRUE)
  )
```
![image](https://user-images.githubusercontent.com/19331059/38077233-3746dece-3330-11e8-8df8-3e1d4facf09b.png)
However, when adding a facet, the old issue of overlap between axis titles and labels persists:

 ```r
mpg_plot_faceted <- mpg_plot + facet_wrap(. ~ fl)

ggplotly(mpg_plot_faceted) %>% 
  layout( 
  xaxis = list(automargin=TRUE), 
  yaxis = list(automargin=TRUE)
  )
```
![image](https://user-images.githubusercontent.com/19331059/38077250-4a35f40c-3330-11e8-9fcb-896cf6167adf.png)

Thanks,

Henry

For reference, the original plotly issue and related fix:

https://github.com/plotly/plotly.js/issues/1504
https://github.com/plotly/plotly.js/pull/2243

**Comment by cpsievert** [comment]
I believe automargins only account for axis titles/labels, not annotations, which is currently the only way to implement axis titles for facetted plots

**Comment by Nova-Scotia** [comment]
+1. I tried to fix this issue based on [this post ](https://stackoverflow.com/questions/42763280/r-ggplot-and-plotly-axis-margin-wont-change) but wasn't successful.

**Comment by MeganBeckett** [comment]
I'm also having issues with faceted plots when converting from ggplot to ggplotly. Does anyone have any solutions?

**Comment by Nova-Scotia** [comment]
Correction: that post [https://stackoverflow.com/questions/42763280/r-ggplot-and-plotly-axis-margin-wont-change ](https://stackoverflow.com/questions/42763280/r-ggplot-and-plotly-axis-margin-wont-change) I mentioned does provide a solution, you may just have to play around a bit with the numbers, and determine which label you want to move.

**Comment by cpsievert** [comment]
Note that `plotly_json()` can be helpful for identifying which annotation you want to modify

**Comment by jfernandez903** [comment]
Based on the post that @Nova-Scotia mentioned, I created a simple function that can make it less of a hassle if you have multiple plots that you are creating:

`layout_ggplotly <- function(gg, x = -0.02, y = -0.08){
  # The 1 and 2 goes into the list that contains the options for the x and y axis labels respectively
  gg[['x']][['layout']][['annotations']][[1]][['y']] <- x
  gg[['x']][['layout']][['annotations']][[2]][['x']] <- y
  gg
}`
you can pipe your ggplotly output into this function so you don't have to name each plot you make in order to adjust the axis labels

**Comment by bobidou23** [comment]
still relatively new to coding so I might be completely misunderstanding something, but it seems to me that ggplots are now constructed differently and that the gg[['x']][['layout']][['annotations']][[1]][['y']] hack no longer works...

Seems to me that p[["theme"]][["text"]] controls the x-axis text, but none of them adjust the y=positioning.

![スクリーンショット 2019-08-02 午後0 40 06](https://user-images.githubusercontent.com/51970305/62390007-48bdcf00-b52f-11e9-95de-909c7f215e27.png)
![スクリーンショット 2019-08-02 午後0 38 33](https://user-images.githubusercontent.com/51970305/62390008-48bdcf00-b52f-11e9-853f-e287ee7a3d37.png)

**Comment by dhodge** [comment]
The layout_ggplotly annotations method doesn't really work for all screen sizes, which is what I'd like to do so that we can integrate ggplotly with my shiny apps. It'd be amazing if this was able to be fixed

**Comment by DmitriiIshutin** [comment]
> Based on the post that @Nova-Scotia mentioned, I created a simple function that can make it less of a hassle if you have multiple plots that you are creating:
> 
> ```
> layout_ggplotly <- function(gg, x = -0.02, y = -0.08){
>   # The 1 and 2 goes into the list that contains the options for the x and y axis labels respectively
>   gg[['x']][['layout']][['annotations']][[1]][['y']] <- x
>   gg[['x']][['layout']][['annotations']][[2]][['x']] <- y
>   gg
> }
> ```
> 
> you can pipe your ggplotly output into this function so you don't have to name each plot you make in order to adjust the axis labels

I noticed this function works correctly only when x and y axis titles exist. If either of those is missing -- for example, as a result of `theme(axis.title.x = element_blank())` -- then positional reference using `...[[1]]...` and `...[[2]]...` refers to wrong titles / annotations.

**Comment by pat-alt** [comment]
Props to @cpsievert @Nova-Scotia @jfernandez903 - all very helpful! When using `facet_grid` the legend overlaps with the plot. If you run into this issue, you can adapt @jfernandez903`s function as follows:

```r
layout_ggplotly <- function(gg, x = -0.1, y = -0.05, x_legend=1.05, y_legend=0.95, mar=list(l=50, r=150)){
  # The 1 and 2 goes into the list that contains the options for the x and y axis labels respectively
  gg[['x']][['layout']][['annotations']][[1]][['y']] <- x
  gg[['x']][['layout']][['annotations']][[2]][['x']] <- y
  gg[['x']][['layout']][['annotations']][[11]][['x']] <- x_legend
  gg[['x']][['layout']][['legend']][['y']] <- y_legend
  gg[['x']][['layout']][['legend']][['x']] <- x_legend
  gg %>% layout(margin = mar)
}
```

Still a bit fiddly and you'll likely have to play with the coordinate values. More generally `plotly_json()` really helps identifying what's wrong with your layout as @cpsievert suggested.

**Comment by johnvnte** [comment]
I had a similar issue when using linebreaks within the label title

<img width="60" alt="Bildschirmfoto 2021-02-08 um 13 34 43" src="https://user-images.githubusercontent.com/63004063/107220567-c7dc6f00-6a12-11eb-8ca2-76437609699f.png">

My ggplotly object does not have an `annotation` parameter. Instead I wrote a small function that allows you to adjust the margins instead. 

```r
SetPlotlyMargin <- function(plotly,
                                location = "l",
                                value = 0) {
  
  # Change location
  plotly[["x"]][["layout"]][["margin"]][[location]] <- value

  return(plotly)
}
```

By setting value for the left-margin (i.e. location = "l") greater the previous one (from default 33 to 50) allowed me to get the desired separation

```r
ggplot() +
     ... %>%
     ggplotly(.) %>%
     SetPlotlyMargin(., location = "l", value = 50)
```

<img width="84" alt="Bildschirmfoto 2021-02-08 um 13 33 49" src="https://user-images.githubusercontent.com/63004063/107220785-0a9e4700-6a13-11eb-81d0-7a4238e71f0d.png">

**Comment by cpsievert** [comment]
#1975 should mostly address this issue (please open a new issue if you're still struggling with it)
