### ISSUE TITLE
Legend title value ignored in barplot

### ISSUE THREAD

**Issue by heimannch** [plotly/plotly.R#1851]
Setting a legend title with `layout.legend.title.text` does not change the default legend title of a barplot. In addition the default legend title is different when bars are colored based on numerical values.

```r
library(plotly)
library(magrittr)


  # Create some data
my_data <- data.frame(
  x_axis = c("A", "B", "C"),
  y_axis = c(5, 10, 15),
  stringsAsFactors = FALSE
)

#bars are colored based on the categorical data - legend title is absent
plotly::plot_ly(
  my_data,
  x = ~x_axis,
  y = ~y_axis,
  color = ~factor(x_axis),
  type = 'bar'
) %>%
 plotly::layout(
    legend = list(
      title = list(text = "Legend Title")))
```
![image](https://user-images.githubusercontent.com/32350126/93246741-0f9bea80-f742-11ea-9c03-bc07a89bd49e.png)

```r
#bars are colored based on the numeric data - legend title is not changed
plotly::plot_ly(
  my_data,
  x = ~x_axis,
  y = ~y_axis,
  color = ~y_axis,
  type = 'bar'
) %>%
  plotly::layout(
    showlegend = TRUE,
    legend = list(
      title = list(text = "Legend Title")))
```
![image](https://user-images.githubusercontent.com/32350126/93246785-20e4f700-f742-11ea-86fc-7589f1238832.png)

**Comment by heimannch** [comment]
I realized that I was running this code on plotly_4.9.1. Updating to plotly 4.9.2.1 solved the issue of setting legend titles when color is based on a categorical value. The behavior in the second plot, where bar colors are based on a continuous variable and the legend title is not changed, remains. 

For an updated reprex:

```
library(plotly)
library(magrittr)


 # Create some data
my_data <- data.frame(
  myx_axis = c("A", "B", "C"),
  myy_axis = c(5, 10, 15),
  stringsAsFactors = FALSE
)

#bars are colored based on the numeric data - legend title is not changed
plotly::plot_ly(
  my_data,
  x = ~myx_axis,
  y = ~myy_axis,
  type = 'bar',
  color = ~myy_axis
) %>%
  plotly::layout(
    showlegend = TRUE,
    legend = list(
      title = list(text = "Legend Title")))
```
![image](https://user-images.githubusercontent.com/32350126/93652196-10927d80-f9c9-11ea-8a9d-3b78b6698964.png)

**Comment by aviezerl** [comment]
You can use `plotly::colorbar`:

```r
plotly::plot_ly(
      my_data,
      x = ~x_axis,
      y = ~y_axis,
      color = ~y_axis,
      type = 'bar'
    ) %>%
    plotly::colorbar(title = "Legend Title")
```
![newplot (3)](https://user-images.githubusercontent.com/18175550/171611505-74eab6be-591b-40ad-864c-dcbb4982347a.png)

**Comment by heimannch** [comment]
@aviezerl, that works, thanks!
