### ISSUE TITLE
ggridges not implemented for ggplotly

### ISSUE THREAD

**Issue by arielhgl** [plotly/plotly.R#1912]
---
I am trying to input a ggplot object using the 'geom_density_ridges_gradient' layer, extracted from ggridges package.
However there is a Warning message saying that a function of this package has yet to be implemented in plotly, more specifically:
'In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_GeomDensityRidgesGradient() has yet to be implemented in plotly.'
After that it redirected me to this github issues website for plotly saying to load my example code, so here it is:
This is the table src_dest_prob
source_floor dest_floor llamadas journey   prob
   <chr>        <chr>         <int> <chr>    <dbl>
 1 L1           38             4455 L1-38   0.116 
 2 38           L1             3527 38-L1   0.0916
 3 36           L1             1939 36-L1   0.0503
 4 L1           36             1808 L1-36   0.0469
 5 40           L1             1317 40-L1   0.0342
 6 L1           40             1241 L1-40   0.0322
 7 36           38             1083 36-38   0.0281
 8 38           43             1076 38-43   0.0279
 9 L1           50             1053 L1-50   0.0273
10 50           L1             1022 50-L1   0.0265

```r
g <- src_dest_prob %>% ggplot(aes(x = prob, y = source_floor, fill = stat(x))) + 
  geom_density_ridges_gradient()+
  scale_fill_viridis_c(name = 'probabilidad', option = 'E'){
plotly::ggplotly(g)
```

**Comment by alikhuseynov** [comment]
same here, it would great to get `plotly` support for `ggridges`. 
Here is related PR #1087 but looks like `ggjoy` branch is no longer supported.
Any updates on this from plotly developers would be appreciated.
Many Thanks!
