### ISSUE TITLE
`ggplotly` fails with an empty layer of `geom_vline`

### ISSUE THREAD

**Issue by jarauh** [plotly/plotly.R#1947]
`ggplotly` fails when there is a `geom_vline`-layer that does not contain any lines.  For me, this happens in a setting where I have a function that computes a set of x-values at which I want to have vertical lines.  Sometimes it happens that no vertical line is needed, and then `ggplotly` fails with the following error message:

> Fehler in fix.by(by.y, y) : 'by' must specify a uniquely valid column

Minimal example:
```r
do_plot <- function(xintercepts) {
  ggplot(mtcars, aes(mpg, carb)) + geom_point() +
    geom_vline(xintercept = xintercepts)
}
plotly::ggplotly(do_plot(23))        # works fine
plotly::ggplotly(do_plot(c(15, 25))) # works fine
plotly::ggplotly(do_plot(numeric())) # produces error (but works without call to ggplotly)
```

**Comment by dereckdemezquita** [comment]
I have the same issue; `ggplot2` works well as is but when passed to `plotly` it fails - expected behaviour is no vertical line drawn but the rest of the plot yes.

**Comment by dereckdemezquita** [comment]
I checked out the source code I believe this is where the failure is occurring; I will tinker with this today a bit:

```r
#' @export
to_basic.GeomVline <- function(data, prestats_data, layout, params, p, ...) {
  # ugh, we can't trust the group here
  data$group <- do.call(paste,
    data[!grepl("group", names(data)) & !vapply(data, anyNA, logical(1))]
  )
  y <- if (inherits(p$coordinates, "CoordFlip")) "x" else "y"
  lay <- tidyr::pivot_longer(
    data = layout$layout, cols = paste0(y, c("_min", "_max")), values_to = y, names_to = "variable"
  ) 
  lay <- as.data.frame(lay)
  data <- merge(lay[c("PANEL", y)], data, by = "PANEL")
  data[["y"]] <- data[[y]]
  data[["x"]] <- data$xintercept
  prefix_class(data, c("GeomVline", "GeomPath"))
}
```

**Comment by dereckdemezquita** [comment]
This function is attempting to merge these two objects:

```r
data <- merge(lay[c("PANEL", y)], data, by = "PANEL")
```

I am browsing here and see that the data object is empty, and thus it cannot be merged; this will obviously throw an error. Indeed, this is the source of the error.

Can someone tell me the expected behaviour here; what should we do? A tryCatch or return some kind of default/empty object?

If someone can help me understand the convention of what to return here I'll fix it and submit a pull request for this today.

```
Browse[1]> lay[c("PANEL", y)]
  PANEL         y
1     1  5354.531
2     1 12343.073

Browse[1]> data
[1] group
<0 rows> (or 0-length row.names)
```
