### ISSUE TITLE
Legend incorrectly captured

### ISSUE THREAD

**Issue by danton267** [plotly/plotly.R#2007]
```

library(plotly)
library(ggnet)
library(network)
library(sna)
library(ggplot2)

# random graph
net = rgraph(10, mode = "graph", tprob = 0.5)
net = network(net, directed = FALSE)

net %v% "phono" = ifelse(letters[1:10] %in% c("a", "e", "i"), "vowel", "consonant")


p <- ggnet2(net, color = "phono")

ggplotly(p)
```

Legend results in `(1,contant,19,9) and (1,vowel,19,9)` instead of `contant and vowel`

**Comment by moutikabdessabour** [comment]
This is caused by `ggplotly` taking in all the aesthetics even if they have only  value. I don't know if this is the correct behavior or not? @cpsievert. I'll have a patch ready by tomorrow morning.

**Comment by cpsievert** [comment]
@moutikabdessabour this seems like a tricky issue to fix without introducing other regressions, have you looked into it at all?
