### ISSUE TITLE
geom_GeomTextWordcloud() not working

### ISSUE THREAD

**Issue by danton267** [plotly/plotly.R#2019]
```

library(plotly)
library(ggwordcloud)

data("love_words_small")

p <- ggplot(love_words_small, aes(label = word)) +
  geom_text_wordcloud()

ggplotly(p)
```

And other examples from here are not working: https://cran.r-project.org/web/packages/ggwordcloud/vignettes/ggwordcloud.html

**Comment by moutikabdessabour** [comment]
Implementing a solution for this would take a lot of time as pointed out by @cpsievert in #2025 . As it is built on top of the grid package.

**Comment by cpsievert** [comment]
Yea, and another reason why I don't think it will ever make sense to support conversion of this class of extension (including #2018) is that the results change with the size of the R graphics device, and so we'd have to essentially re-implement these extensions client-side for them to work correctly on resize, which would be a very big project.

Ideally, https://github.com/plotly/plotly.js/issues/4674 would get implemented in a way that would support these extensions, but that also seems difficult/unlikely
