### ISSUE TITLE
Subplots do not work

### ISSUE THREAD

**Issue by danton267** [plotly/plotly.R#2020]
None of these examples work: https://cran.r-project.org/web/packages/egg/vignettes/Ecosystem.html

None of these work either: https://ggplot2-book.org/arranging-plots.html

**Comment by cpsievert** [comment]
Closing for the same reasons mentioned here https://github.com/plotly/plotly.R/issues/2028#issuecomment-956431432 (these packages work at the `{grid}` level, which would require a huge amount of work to support).

If you're struggling to come up with a `subplot()` based workaround for any particular example, let me know which one.
