### ISSUE TITLE
pheatmap() not implemented

### ISSUE THREAD

**Issue by danton267** [plotly/plotly.R#2026]
```

library(plotly)
library(ggplot2)
library(pheatmap)

dat <- matrix(rnorm(100, 3, 1), ncol=10)
names(dat) <- paste("X", 1:10)

p <- pheatmap(dat, display_numbers = T)

ggplotly(p)
```

yields the following error:

```
Error in UseMethod("ggplotly", p) : 
  no applicable method for 'ggplotly' applied to an object of class "pheatmap"
```

**Comment by cpsievert** [comment]
Looks as though `{pheatmap}` is implemented at the `{grid}` level, so like #2020 and #2028, it won't make sense to add support for it any time soon.

As a workaround, I'd suggest using the `{heatmaply}` package instead, which appears to be quite similar
