### ISSUE TITLE
latex2exp not supported

### ISSUE THREAD

**Issue by danton267** [plotly/plotly.R#2027]
```
library(plotly)
library(latex2exp)
library(ggplot2)

p <- qplot(1, "A")+
     ylab(TeX("Formula: $\\frac{2hc^2}{\\lambda^\\beta}$"))+
     xlab(TeX("$\\alpha$"))

ggplotly(p)
```
yields following error
```
Error in unique.default(x) : unimplemented type 'expression' in 'duplicated'
```

**Comment by cpsievert** [comment]
Whoops, #2030 doesn't actually fix this problem, so I've reverted it in https://github.com/plotly/plotly.R/commit/15807cf75a092cd17d1c4a5bc9b5dffe56057941. 

The problem derives from the fact that by doing `library(latex2exp)` _after_ `library(plotly)` will make `TeX()` resolve to `latex2exp::TeX()`, not `plotly::TeX()`

```r
> library(plotly)
> library(latex2exp)

Attaching package: ‘latex2exp’

The following object is masked from ‘package:plotly’:

    TeX
> p <- qplot(1, "A") +
+   ylab(TeX("Formula: $\\frac{2hc^2}{\\lambda^\\beta}$")) +
+   xlab(TeX("$\\alpha$"))
> ggplotly(p)
Error in unique.default(x) : 
  unimplemented type 'expression' in 'duplicated'
```


So, the actual fix must come from the user code by changing `TeX()` to `plotly::TeX()`
