### ISSUE TITLE
multiple axes dislay not working

### ISSUE THREAD

**Issue by danton267** [plotly/plotly.R#2028]
None of these plots display seconds axes properly: https://www.r-graph-gallery.com/line-chart-dual-Y-axis-ggplot2.html

**Comment by cpsievert** [comment]
T don't think `{plotly}` will ever be able to support conversion of `{patchwork}` code (unless we undertook a _huge_ rewrite to convert objects at the `{grid}` level).

That being said, in most cases, `subplot()` can be used to do the same thing that `{patchwork}` operators `+`, `\`, etc. do

**Comment by cpsievert** [comment]
```r
library(ggplot2)
library(dplyr)
library(hrbrthemes)

# Build dummy data
data <- data.frame(
  day = as.Date("2019-01-01") + 0:99,
  temperature = runif(100) + seq(1,100)^2.5 / 10000,
  price = runif(100) + seq(100,1)^1.5 / 10
)

# Most basic line chart
p1 <- ggplot(data, aes(x=day, y=temperature)) +
  geom_line(color="#69b3a2", size=2) +
  ggtitle("Temperature: range 1-10") +
  theme_ipsum()
  
p2 <- ggplot(data, aes(x=day, y=price)) +
  geom_line(color="grey",size=2) +
  ggtitle("Price: range 1-100") +
  theme_ipsum()

subplot(p1, p2)
```
