### ISSUE TITLE
Changing position of axis labes does not work

### ISSUE THREAD

**Issue by danton267** [plotly/plotly.R#2029]
```
library(plotly)
library(ggplot2)

p <- ggplot(mtcars) +
  geom_point(aes(disp, mpg)) +
  scale_x_continuous(position = 'top')

ggplotly(p)
```

`scale_x_continuous(position = 'top'` should move x-labels to the top, however, it does nothing.

**Comment by cpsievert** [comment]
Unfortunately, I don't think it makes sense to implement `position` without also adding support for subtitles, captions, and footnotes. There is a work-in-progress for this in https://github.com/plotly/plotly.R/pull/929 and I'd be happy to take it over the finish line if @jackparmer wants to support it
