### ISSUE TITLE
plotGlPixelRatio not respected by image button download

### ISSUE THREAD

**Issue by j-andrews7** [plotly/plotly.R#2050]
The `plotGlPixelRatio` config setting is not respected when using a scattergl trace and attempting to download the image in svg format via the image download button. This option was previously broken in older versions of plotly but was [fixed](https://github.com/plotly/plotly.js/pull/5500) and should have made its way into the R version now as well.

I expect this is an issue with RStudio's lack of webGL rendering as noted in the warning, but opening the figure in a new browser window has the same issue. 

```r
library(plotly)
 
fig <- plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length, type = "scattergl", mode = "markers") %>%
    config(plotGlPixelRatio = 10, toImageButtonOptions = list(format = "svg"))

fig2 <- plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length, type = "scattergl", mode = "markers") %>% 
    config(plotGlPixelRatio = 1, toImageButtonOptions = list(format = "svg"))
```

These images downloaded from a browser window will be the same.

**Comment by cpsievert** [comment]
Have you tried this with the latest version of plotly?
