### ISSUE TITLE
`gather_()` will likely become defunct in tidyr 1.2.0

### ISSUE THREAD

**Issue by DavisVaughan** [plotly/plotly.R#2088]
We are planning on moving the lazyeval versions of the main tidyr verbs to the defunct stage in the next version of tidyr. They have been deprecated for awhile now, and the NSE versions can do everything the lazyeval versions were meant to help with. See https://github.com/tidyverse/tidyr/pull/1281 for more information.

Could you please remove your usage of `gather_()` from plotly?

**Comment by cpsievert** [comment]
Was `gather_()` ever soft-deprecated? Seems extreme to remove it with no prior warning.

**Comment by DavisVaughan** [comment]
Oh good point. Most of the lazyeval functions [here](https://github.com/tidyverse/tidyr/pull/1281/files) were soft-deprecated already, but `gather_()` is one that wasn't. Maybe we should start by soft-deprecating them all in the next release.

**Comment by DavisVaughan** [comment]
So, I'd say nothing for you to _immediately_ do, but I do think it would be a good idea to move away from `gather_()` in the near ish future. Either to `gather()` or `pivot_longer()`. I will leave it up to you as to whether or not you want to keep this issue open as a stub for that

**Comment by cpsievert** [comment]
Oh definitely, I mainly bring it up out of concern for legacy user code

**Comment by msummersgill** [comment]
Perhaps another good reason to drop remaining "tidyverse" dependencies in favor of base `R` functionality and `data.table` _(whose authors respect the value of long term stability -- haven't seen any issues with `Group2NA` since adding as a dependency 5 years ago)_ implementations? Would be happy to help on a re-factor if you'd like a PR.

**Comment by netique** [comment]
`gather_` is deprecated in `tidyr` 1.2.0+ and now throws a warning whenever using `plotly`. I vote for moving from `gather` to `pivot_longer` as gather itself is superseded.
