### ISSUE TITLE
Plotly 4.10.0 Rendering Tooltips on Bar Chart Bars

### ISSUE THREAD

**Issue by dcont5512** [plotly/plotly.R#2107]
I am running Plotly 4.10.0. When I running the following code from the [Plotly overview website](https://plotly.com/r/bar-charts/) (see 'Bar Chart with Hover Text'), for some reason my tooltips are appearing on the chart itself. This is not however happening when I run 4.9.3. Is this a bug with the new version?

```
library(plotly)

x <- c('Product A', 'Product B', 'Product C')
y <- c(20, 14, 23)
text <- c('27% market share', '24% market share', '19% market share')
data <- data.frame(x, y, text)

fig <- plot_ly(data, x = ~x, y = ~y, type = 'bar', text = text,
        marker = list(color = 'rgb(158,202,225)',
                      line = list(color = 'rgb(8,48,107)',
                                  width = 1.5)))
fig <- fig %>% layout(title = "January 2013 Sales Report",
         xaxis = list(title = ""),
         yaxis = list(title = ""))

fig
```

![newplot (20)](https://user-images.githubusercontent.com/50527979/154137315-857b6069-1e6b-4b87-865a-2f55548e7883.png)

**Comment by trafficonese** [comment]
This is due to an intended change in the JavaScript library.
From now on, you'll have to include the following setting:
`textposition="none"`
