### ISSUE TITLE
Deprecated function gather_()

### ISSUE THREAD

**Issue by mrbladergroen** [plotly/plotly.R#2196]
I get an error upon knitting my R-script:

`gather_()` was deprecated in tidyr 1.2.0.
ℹ Please use `gather()` instead.
ℹ The deprecated feature was likely used in the plotly package.
  Please report the issue at <https://github.com/plotly/plotly.R/issues>.

**Comment by cpsievert** [comment]
You can get rid of the warning by installing the dev version of plotly

```r
remotes::install_github("ropensci/plotly")
```
