### ISSUE TITLE
ggplotly not rendering unicode characters in `scale_shape` correctly

### ISSUE THREAD

**Issue by rocanja** [plotly/plotly.R#2235]
When using unicode characters as shapes eg. `scale_shape_manual(values=c("\u25BC","\u25FC","\u25B2"))` they are rendered correctly with ggplot() but not with ggplotly(). Is ggplotly() not compatible with unicode or is there another workaround?

**Comment by trekonom** [comment]
Added a minimal reproducible example of the issue, which however also shows that using unicode symbols may also fail in `ggplot2` and AFAIK depends on the font family:

``` r
library(ggplot2)
library(plotly, warn=FALSE)

ggplot(mtcars, aes(hp, mpg, shape = factor(cyl))) +
  geom_point(size = 4) +
  scale_shape_manual(values=c("\u25BC","\u25FC","\u25B2"))
```

![](https://i.imgur.com/yW1zQdX.png)

``` r

ggplotly()
```

![](https://i.imgur.com/DSX3bfW.png)

<sup>Created on 2023-02-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rocanja** [comment]
Thanks for pointing out these helpful resources @trekonom !

**Comment by rocanja** [comment]
Following [the reference](https://plotly.com/r/reference/#scatter-marker-symbol) given by @trekonom to the page with the plotly supported symbols, here is the very straightforward solution for a 'filled triangle point-DOWN' for anyone coming across this issue:
`scale_shape_manual(values=c("\U25BC","\U25CF","\U25B2"))` for ggplot plots
`scale_shape_manual(values=c("triangle-down","circle","triangle-up"))` for plotly plots
