### ISSUE TITLE
geom_density_ridges with plotly

### ISSUE THREAD

**Issue by aniskara** [plotly/plotly.R#2322]
Hi, 

I'm trying to work on density plot using geom_density_ridges, it works with ggplot but not with ggplotly. Do you have any suggestion for an alternative or an idea to resolve the issue ?

Thanks 

code :

data_to_plot <- read.csv("density_data.csv")

plot <- ggplot(data_to_plot, aes(x = ncounts, y = celltype, fill = celltype, color = celltype)) +
  geom_density_ridges(alpha = 0.3) +
  facet_grid(gene ~ dataset + sample) +
  theme_ridges() +
  theme(panel.spacing = unit(.05, "lines"),
        panel.border = element_rect(color = "black", fill = NA, size = 1),
        strip.background = element_rect(color = "black", size = 1.2),
        strip.text.x = element_text(margin = margin(0.4, 0.2, 0.4, 0.2, "cm"))) +
  labs(y = NULL)
plot

ggplotly(plot)

![Screenshot 2023-12-06 at 11 56 19 AM](https://github.com/plotly/plotly.R/assets/125394216/1d1112a8-80e3-46cb-8033-b99202c12243)

**Comment by cpsievert** [comment]
`ggplotly()` should mostly work with `{ggridges}` now. You'll need the development version though `remotes::install_github("plotly/plotly.R")`
