### ISSUE TITLE
gather()_ command

### ISSUE THREAD

**Issue by peter-atkinson** [plotly/plotly.R#2323]
I am using the plotly package to convert a ggplot object to a plotly object (using command ggplotly). I get the following warning:

Warning: `gather_()` was deprecated in tidyr 1.2.0.
ℹ Please use `gather()` instead.
ℹ The deprecated feature was likely used in the plotly package.

**Comment by cpsievert** [comment]
I think you might have an outdated version of plotly, but it's hard to know without a reproducible example. Please file a new issue if you still have this problem
